/*
 * try/catch
 * Ошибки фазы парсинга обработать нельзя. Только ошибки фазы выполнения.
 * Объект ошибки
 * try/catch работает только с синхронным кодом
 * Обработка ошибок в асинхронном коде
 */

// console.log('First');

// setTimeout(() => {
//   try {
//     const username = 'Oleksii';

//     username = 'Elva';
//   } catch (err) {
//     console.log(err);
//   }

//   console.log('Hello');
// }, 1000);

// console.log('Second');
